export const FETCH_PLANS = 'FETCH_PLANS';
export const FETCH_PLANS_SUCCESS = 'FETCH_PLANS_SUCCESS';
export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_ORGANISATION = 'FETCH_ORGANISATION';
export const FETCH_ORGANISATION_SUCCESS = 'FETCH_ORGANISATION_SUCCESS';
export const ON_LOAD_PLANS = 'ON_LOAD_PLANS';
export const ON_LOAD_PUBLISH = 'ON_LOAD_PUBLISH';
export const ON_LOAD_RELEASE = 'ON_LOAD_RELEASE';
export const ON_LOAD_FILL = 'ON_LOAD_FILL';



