// Title Länge maixmal 100 Zeichen
// Description Länge maximal 255 Zeichen
// gerne Keywords benutzen
export const LANDING_TITLE = "Dein digitaler Schichtplan online & als App - Staffbite";
export const LANDING_DESCRIPTION = "Wir bieten dir digitale Schichtpläne für die Gastronomie, Hotellerie, den Einzelhandel und viele mehr. Durch einen online Schichtplan und unsere Automatisierung der Befüllung kannst du jede Woche mehrere Stunden Zeit sparen.";
export const SCHICHTPLAN_TITLE = "Staffbite - Unsere Funktionalitäten";
export const SCHICHTPLAN_DESCRIPTION = "Hier findest du einen Überblick über unsere Funktionalitäten. Von deinen ersten Schritten zum digitalen Schichtplan, der automatisierten Befüllung bis zur Veröffentlichung des fertigen Plans. Natürlich gibt es auch jede Menge Vorteile für dein Team!";
export const ERSTEANMELDUNG_TITLE = "Staffbite - Die erste Anmeldung";
export const ERSTEANMELDUNG_DESCRIPTION = "Auf dieser Seite zeigen wir dir die ersten Schritte mit Staffbite.";
export const TEAMVERWALTEN_TITLE = "Staffbite - Verwalte dein Team";
export const TEAMVERWALTEN_DESCRIPTION = "Mit Staffbite behälst du dein Team einfach und übersichtlich im Blick.";
export const SCHICHTPLANERSTELLEN_TITLE = "In wenigen Schritten deinen Schichtplan online erstellen. - Staffbite";
export const SCHICHTPLANERSTELLEN_DESCRIPTION = "Erstelle deinen individuellen Schichtplan innerhalb kürzester Zeit.";
export const VERFÜGBARKEITENEINTRAGEN_TITLE = "Staffbite - Verfügbarkeiten eintragen";
export const VERFÜGBARKEITENEINTRAGEN_DESCRIPTION = "Dein Team kann sich jederzeit online in den Schichtplan eintragen - per Smartphone, Tablet oder Laptop.";
export const AUTOMATISIERTE_SCHICHTPLANUNG_TITLE = "Fertige Schichtpläne in wenigen Sekunden? - Automatisiere deine Schichtplanung";
export const AUTOMATISIERTE_SCHICHTPLANUNG_DESCRIPTION = "Mit Staffbite kannst du bequem und in wenigen Sekunden deinen Schichtplan automatisiert stellen lassen.";
export const SCHICHTPLAN_VEROEFFENTLICHEN_TITLE = "Staffbite - Schichtpläne veröffentlichen mit nur einem Klick.";
export const SCHICHTPLAN_VEROEFFENTLICHEN_DESCRIPTION = "Benachrichtige dein Team mit nur einem Klick, wenn ein neuer Schichtplan veröffentlicht wurde."
export const TEAM_VORTEILE_TITLE = "Staffbite - Erfahre die Vorteile von einer digitalen Schichtplanung Online und per App.";
export const TEAM_VORTEILE_DESCRIPTION = "Mit Staffbite kann dein Team von überall auf ihre Schichtpläne online und per App zugreifen. Kein Zettel oder WhatsApp-Gruppen."
export const THEMEN_TITLE = "Wie funktioniert eine moderne Schichtplanung in 2022? - Anleitung | Blog";
export const THEMEN_DESCRIPTION = "Auf dieser Seite beantworten wir Fragen, geben Tipps & Tricks an die Hand und halten dich auf dem laufenden!";
export const THEMEN_CLOUDSERVICE_TITLE = "Staffbite - Dein Online Schichtplan durch die Cloud";
export const THEMEN_CLOUDSERVICE_DESCRIPTION = "In diesem Beitrag gehen wir auf die Frage ein warum Staffbite ein Cloud Service ist und welche Vorteile dies für unsere Kunden hat.";
export const THEMEN_AUTOMATISIERUNG_TITLE = "Wie funktioniert eine automatisierte Befüllung deiner Schichtpläne?";
export const THEMEN_AUTOMATISIERUNG_DESCRIPTION = "In diesem Beitrag stelle ich dir die automatisierte Befüllung deiner Schichtpläne mit Staffbite vor.";
export const THEMEN_SCHICHTPLANERSTELLEN_TITLE = "Wie erstelle ich einen Schichtplan in 2022? Online, mit Excel & co."
export const THEMEN_SCHICHTPLANERSTELLEN_DESCRIPTION = "In diesem Beitrag zeige ich dir wie du eine Vorlage für deinen individuellen Schichtplan erstellen kannst.";
export const THEMEN_SCHICHTPLANVORLAGE_TITLE = "In wenigen Schritten eine Schichtplanvorlage erstellen. (Schritt für Schritt)";
export const THEMEN_SCHICHTPLANVORLAGE_DESCRIPTION = "In diesem Beitrag zeige ich dir die Vor-und Nachteile von drei verschiedenen Möglichkeit zur Erstellung deiner Schichtpläne.";
export const THEMEN_MONATSPLANUNG_TITLE = "Wie funktioniert Schichtplanung für einen ganzen Monat?";
export const THEMEN_MONATSPLANUNG_DESCRIPTION = "In diesem Beitrag zeige ich dir wie du mit deiner Vorlage einen Schichtplan für den ganzen Monat erstellen kannst.";
export const THEMEN_INDIVIDUELLERSCHICHTPLAN_TITLE = "Schritt für Schritt zu deinem individuellen Schichtplan.";
export const THEMEN_INDIVIDUELLERSCHICHTPLAN_DESCRIPTION = "In diesem Beitrag zeige ich dir wie du deinen Schichtplan im Detail individualisieren kannst.";
export const THEMEN_AUTOMATISIERTEBEFÜLLUNG_TITLE = "Staffbite - Schritt für Schritt: Automatisierte Befüllung starten";
export const THEMEN_AUTOMATISIERTEBEFÜLLUNG_DESCRIPTION = "In diesem Beitrag zeige ich dir Schritt für Schritt wie du die automatisierte Befüllung starten kannst.";
export const THEMEN_ANPASSUNGEN_TITLE = "Staffbite - Schritt für Schritt: Anpassungen am Schichtplan";
export const THEMEN_ANPASSUNGEN_DESCRIPTION = "In diesem Beitrag zeige ich dir Schritt für Schritt wie du Anpassungen an deinem Schichtplan vornehmen kannst.";
export const THEMEN_VERÖFFENTLICHUNG_TITLE = "Staffbite - Schritt für Schritt: Schichtplan veröffentlichen";
export const THEMEN_VERÖFFENTLICHUNG_DESCRIPTION = "In diesem Beitrag zeige ich dir Schritt für Schritt wie du deinen fertigen Schichtplan mit deinem Team teilst.";
export const THEMEN_EINTRAGEN_TITLE = "Staffbite - Schritt für Schritt: Eintragen in den Schichtplan";
export const THEMEN_EINTRAGEN_DESCRIPTION = "In diesem Beitrag zeige ich dir Schritt für Schritt wie dein Team sich in den Schichtplan einträgt.";
export const THEMEN_TEAMEINLADEN_TITLE = "Staffbite - Schritt für Schritt: Team einladen";
export const THEMEN_TEAMEINLADEN_DESCRIPTION = "In diesem Beitrag zeige ich dir Schritt für Schritt wie du dein Team zu Staffbite einlädst.";
export const IMPRESSUM_TITLE = "Staffbite - Impressum";
export const IMPRESSUM_DESCRIPTION = "Hier findest du Kontaktmöglichkeiten und vieles mehr.";
export const FAQ_TITLE = "Staffbite - FAQ";
export const FAQ_DESCRIPTION = "Die häufigsten Fragen werden hier direkt beantwortet. Vom kostenlosen Probemonat über Schichtplan Vorlagen und dem Schichten tauschen wird alles beantwortet.";
export const KONTAKT_TITLE = "Staffbite - Kontakt";
export const KONTAKT_DESCRIPTION = "Bei Fragen kannst du dich jederzeit an uns wenden. Lass uns einfach deine Kontaktdaten da und wir melden uns schnellstmöglich bei dir!";
export const ABOUTUS_TITLE = "Staffbite - Über uns";
export const ABOUTUS_DESCRIPTION = "Du willst mehr über die beiden Gründer von Staffbite erfahren? Dann bist du hier genau richtig.";
export const AV_TITLE = "Staffbite - Auftragsdatenverarbeitung";
export const AV_DESCRIPTION = "Hier findest du unsere Auftragsdatenverarbeitung.";