export const ONBOARDING_TEAM_INVITE = "Hier kannst du einen neuen Mitarbeiter einladen!";
export const ONBOARDING_TEAM_OVERVIEW = "Hier werden in Zukunft deine Mitarbeiter aufgelistet!";
export const ONBOARDING_OVERVIEW_TEAM = "Hier werden in Zukunft deine Mitarbeiter aufgelistet!";
export const ONBOARDING_OVERVIEW_SHIFTRADE = "Hier werden in Zukunft die Tauschanfragen deiner Mitarbeiter angezeigt!";
export const ONBOARDING_OVERVIEW_SHIFTPLAN = "Hier wird in Zukunft dein aktueller Schichtplan angezeigt.";
export const ONBOARDING_SHIFTPLAN_VORLAGE_ERSTELLEN = "Hier kannst du eine neue Vorlage für deinen Schichtplan erstellen.";
export const ONBOARDING_SHIFTPLAN_VORLAGE = "In diesem Reiter werden in Zukunft deine Schichtplanvorlagen angezeigt.";
export const ONBOARDING_SHIFTPLAN_EINTRAGEN = "In diesem Reiter werden in Zukunft deine Schichtpläne anzeigt, auf die sich deine Mitarbeiter bewerben können.";
export const ONBOARDING_SHIFTPLAN_UEBERPRUEFUNG = "Hier wird in Zukunft angezeigt, wie dein Schichtplan nach der automatierten Befülung aussieht.";
export const ONBOARDING_SHIFTPLAN_VEROEFFENTLICHUNG = "Hier werden in Zukunft deine veröffentlichten Schichtpläne angezeigt.";
export const ONBOARDING_EINSTELLUNGEN_NAV_BETRIEB = "Hier kannst Informationen rund um einen Betrieb festhalten.";
export const ONBOARDING_EINSTELLUNGEN_NAV_SHIFTPLAN = "Hier kannst du später Anpassungen der autotmatisierten Befüllung vornehmen.";
export const ONBOARDING_EINSTELLUNGEN_BETRIEB_NAME = "Hier kannst du deinem Betrieb einen passenden Namen geben.";
export const ONBOARDING_EINSTELLUNGEN_NAME = "Hier werden in Zukunft deine veröffentlichten Schichtpläne angezeigt.";
export const ONBOARDING_EINSTELLUNGEN_STUNDENERFASSUNG = "Hier werden in Zukunft deine veröffentlichten Schichtpläne angezeigt.";
export const ONBOARDING_EINSTELLUNGEN_POSITIONEN = "Trage hier die Positionen deines Betriebs ein. z.B. Service, Küche, Bar.";
export const ONBOARDING_EINSTELLUNGEN_SHIFTPLAN_REVERSE = "Hier werden in Zukunft deine veröffentlichten Schichtpläne angezeigt.";
export const ONBOARDING_EINSTELLUNGEN_SHIFTPLAN_ORDER = "Hier werden in Zukunft deine veröffentlichten Schichtpläne angezeigt.";
export const ONBOARDING_EMPLOYEE_OVERVIEW_APPLICATIONS = "Hier kannst du sehen, wie oft du dich diese Woche beworben hast."
export const ONBOARDING_EMPLOYEE_OVERVIEW_TRADE_SHIFT = "Hier kannst du sehen, wie der Status deiner aktuellen Tauschanfragen aussieht."
export const ONBOARDING_EMPLOYEE_OVERVIEW_SHIFTPLAN = "Hier kannst du deinen aktuellen Schichtplan sehen."
export const ONBOARDING_EMPLOYEE_EINTRAGEN = "Hier kannst du dich in Zukunft für Schichten eintragen."
export const ONBOARDING_EMPLOYEE_SCHICHTPLAN = "Hier kannst du in Zukunft deine Schichten einsehen."
export const ONBOARDING_EMPLOYEE_NAME = "Hier kannst du dein Profil noch etwas verfeinern."
export const ONBOARDING_EMPLOYEE_SHIFTS_PER_WEEK = "Hier kannst du in Zukunft deine Schichten einsehen."
export const ONBOARDING_EMPLOYEE_PICTURE = "Hier kannst du in Zukunft deine Schichten einsehen."
