export const ONBOARDING_TEAM_INVITE = "Hier kannst du neue Mitarbeiter einladen!";
export const ONBOARDING_TEAM_OVERVIEW = "Hier wird dein gesamtes Team aufgelistet. Klicke auf ein Teammitglied um detaillierte Informationen zu erhalten.";
export const ONBOARDING_OVERVIEW_TEAM = "Hier kannst du auf einen Blick sehen wie groß dein Team derzeit ist.";
export const ONBOARDING_OVERVIEW_SHIFTRADE = "Hier werden in Zukunft die Tauschanfragen deiner Mitarbeiter angezeigt!";
export const ONBOARDING_OVERVIEW_SHIFTPLAN = "Hier wird in Zukunft dein aktueller Schichtplan angezeigt.";
export const ONBOARDING_SHIFTPLAN_VORLAGE_ERSTELLEN = "Klicke auf diesen Button, um eine neue Vorlage für deinen Schichtplan zu erstellen. Deine individuellen Vorlagen kannst du jederzeit wiederverwenden!";
export const ONBOARDING_SHIFTPLAN_VORLAGE = "In diesem Reiter findest du deine Vorlagen. Wenn du zufrieden mit deiner Vorlage bist, kannst du den Schichtplan an dein Team freigeben.";
export const ONBOARDING_SHIFTPLAN_EINTRAGEN = "Hier findest du die Schichtpläne, die du an dein Team freigegeben hast. Du kannst sehen wie sich dein Team eingetragen hat und die Befüllung starten sobald du bereit bist.";
export const ONBOARDING_SHIFTPLAN_UEBERPRUEFUNG = "Nachdem dein Schichtplan automatisiert befüllt wurde, taucht der Plan hier auf. Du kannst noch manuelle Änderungen vornehmen und den Plan abschließend für dein gesamtes Team veröffentlichen.";
export const ONBOARDING_SHIFTPLAN_VEROEFFENTLICHUNG = "Hier werden deine fertigen & veröffentlichten Schichtpläne angezeigt.";
export const ONBOARDING_EINSTELLUNGEN_NAV_BETRIEB = "Hier kannst du die wichtigsten Informationen rund um deinen Betrieb festhalten!";
export const ONBOARDING_EINSTELLUNGEN_NAV_SHIFTPLAN = "In diesem Reiter findest du weitere Einstellungen, die die automatisierte Befüllung deiner Schichtpläne beeinflussen.";
export const ONBOARDING_EINSTELLUNGEN_BETRIEB_NAME = "Trage hier den Namen deines Betriebs ein.";
export const ONBOARDING_EINSTELLUNGEN_NAME = "Hier werden in Zukunft deine veröffentlichten Schichtpläne angezeigt.";
export const ONBOARDING_EINSTELLUNGEN_SPEICHERN = "Wenn du fertig mit deinen Änderungen bist, dann klicke hier auf Speichern.";
export const ONBOARDING_EINSTELLUNGEN_STUNDENERFASSUNG = "Hier werden in Zukunft deine veröffentlichten Schichtpläne angezeigt.";
export const ONBOARDING_EINSTELLUNGEN_POSITIONEN = "Hier kannst du festlegen welche Positionen (z.B. Kasse, Küche, Service) es in deinem Betrieb gibt! Diese Postionen brauchst du später, um deinen Schichtplan individuell zu gestalten.";
export const ONBOARDING_EINSTELLUNGEN_SHIFTPLAN_REVERSE = "Hier werden in Zukunft deine veröffentlichten Schichtpläne angezeigt.";
export const ONBOARDING_EINSTELLUNGEN_SHIFTPLAN_ORDER = "Hier werden in Zukunft deine veröffentlichten Schichtpläne angezeigt.";
export const ONBOARDING_EMPLOYEE_OVERVIEW_APPLICATIONS = "Hier kannst du auf einen Blick sehen wie oft du dich diese Woche beworben hast. Wenn du auf diese Feld klickst, kommst du direkt zu den aktuellen Schichtplänen."
export const ONBOARDING_EMPLOYEE_OVERVIEW_TRADE_SHIFT = "Hier werden deine Tauschanfragen der aktuellen Woche angezeigt, falls du krank bist oder eine Schicht abgeben musst. Klick einfach auf dieses Feld, um zu den fertigen Schichtplänen zu kommen."
export const ONBOARDING_EMPLOYEE_OVERVIEW_SHIFTPLAN = "Hier kannst du deinen aktuellen Schichtplan sehen."
export const ONBOARDING_EMPLOYEE_EINTRAGEN = "In diesem Reiter findest du die vorbereiteten Schichtpläne. Schau dir den Namen und den Zeitraum links an und suche dir den richtigen Plan aus um dich einzutragen."
export const ONBOARDING_EMPLOYEE_SCHICHTPLAN = "Hier findest du die fertigen Schichtpläne. Wenn ein Plan veröffentlicht wurde, kannst du hier sehen wann du arbeiten musst."
export const ONBOARDING_EMPLOYEE_NAME = "Das hier ist dein Profil. Aktuell kannst du hier noch nicht viel machen, aber das wird sich bald ändern!"
export const ONBOARDING_EMPLOYEE_SHIFTS_PER_WEEK = "Hier kannst du in Zukunft deine Schichten einsehen."
export const ONBOARDING_EMPLOYEE_PICTURE = "Hier kannst du in Zukunft deine Schichten einsehen."
